#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 29 19:03:43 2018

@author: yhilly
"""
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()


x = [[2.]]
m = tf.matmul(x, x)

print (m)